title: Flight Profit Optimizer
description: A comprehensive solution designed to maximize revenue for flight seat assignments using ASP.NET Core 8.0 and dynamic programming.
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
